---
- name: Restart Immich
  community.docker.docker_compose_v2:
    project_src: "{{ immich_base_dir }}"
    state: restarted
  become_user: "{{ username }}"
  tags: [immich, immich-config, immich-deploy]
